### ISSUE TITLE
Fix Wifi

### ISSUE THREAD

**Issue by martincz** [Grarak/android_device_oneplus_plutonium#1]
Add these in device.mk
$(LOCAL_PATH)/wifi/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/qca_cld/WCNSS_qcom_cfg.ini \
$(LOCAL_PATH)/wifi/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/qca_cld/WCNSS_qcom_wlan_nv.bin
https://github.com/MoKee/android_device_oneplus_tocino/commit/ddc1bc5ab6dc51a97a6fe73026ee03130eda8bb8

**Comment by Grarak** [comment]
Picked your commit + https://github.com/Grarak/android_device_oneplus_plutonium/commit/eee449514a99910d275539300c23cf54ff5d57df

Should be cleaner

**Comment by martincz** [comment]
Yep, That's good.
