### ISSUE TITLE
Add missing files for fix boot

### ISSUE THREAD

**Issue by martincz** [Grarak/android_device_oneplus_plutonium#9]
http://review.mfunz.com/#/c/12386/
http://review.mfunz.com/#/c/12387/

**Comment by Grarak** [comment]
These blobs
https://github.com/MoKee/android_device_oneplus_tocino/commit/384db4cb6d78492f2b2310c1c806d6e1f786176e#diff-e18a190ec9e1d301d38ff968dea34a59R445

won't get copied

**Comment by Grarak** [comment]
Don't think your commits will fix booting.
Logcat shows me this
E/art     ( 6875): dlopen("/vendor/lib64/liblocationservice.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "_ZN8loc_core14LocAdapterBase8reportSvER11GpsSvStatusR19GpsLocationExtendedPv" referenced by "liblbs_core.so"...

I will try to reverse engineer some gps blobs.
For now use libloc_core.so from stock to fix booting

**Comment by martincz** [comment]
Yep, you should push com.qualcomm.locaion.apk from official ROM

**Comment by martincz** [comment]
Push this to your /system/priv-app/com.qualcomm.location
https://github.com/MoKee/android_vendor_oneplus_tocino/blob/mkl-mr1/proprietary/priv-app/com.qualcomm.location/com.qualcomm.location.apk

**Comment by Grarak** [comment]
I am using it from stock rom

**Comment by martincz** [comment]
But changed when compile...You can compare them.

**Comment by Grarak** [comment]
what do you mean exactly with changed? Does gps not work for you with prebuilt gps blobs?

**Comment by martincz** [comment]
I compared the original "com.qualcomm.location.apk" and new file when compile finished. they're different. I push origin file, boot successful but gps not work.

**Comment by martincz** [comment]
I do not know what goes wrong :(

**Comment by martincz** [comment]
![aa6](https://cloud.githubusercontent.com/assets/351434/9529939/ace6433e-4d2f-11e5-9c26-56eaa1009856.png)

**Comment by Grarak** [comment]
I copied libloc_core.so and libalarmservice_jni.so from stock, to boot it up. GPS works for me. Weird that your device booted up. My logcat is crying for those two blobs

**Comment by martincz** [comment]
I think I know why... wait me test..

**Comment by martincz** [comment]
We have a wrong certificate....
http://review.mfunz.com/#/c/12389/1/Android.mk

**Comment by Grarak** [comment]
Well does not really matter with it's signed or not.
I've fixed it now. Using an older caf branch works

**Comment by martincz** [comment]
gps working now?

**Comment by Grarak** [comment]
Yes

**Comment by martincz** [comment]
Oh, good news! :+1:
